metabrainz/troi-recommendation-playground

setup.py
LB-739
This is an initial version of setup.py that allows us to upload troi to pypi. We should still address some of the points raised in the above ticket in the future.
=> Add a more detailed setup.py for upload to pypi

troi/cli.py
Took a while to realise that the reason that `list(x)` wasn't working is that there was a function in this file called `list`. This command will now be `troi list-patches`. We can rename the method using click if you want to keep it `list`.
=> Pass all test subcommand arguments and options to pytest

troi/musicbrainz/artist_credit_id_lookup.py, troi/musicbrainz/msb_mapping.py, troi/musicbrainz/related_artist_credits.py
Quick fix to use `params` to pass in a dict of query parameters instead of constructing it manually:
* Requests quotes things for you, so `quote()` isn't needed
* Easier to change parameters if needed without having to faff about with ? and &
* use `r.url` after the request has been made to see the full url with query params if needed
=> Use request's params argument instead of encoding manually

troi/__init__.py, troi/filters.py, troi/listenbrainz/area_random_recordings.py, troi/listenbrainz/recs.py, troi/listenbrainz/stats.py, troi/listenbrainz/tests/test_area_random_recordings.py, troi/listenbrainz/tests/test_recs.py, troi/listenbrainz/tests/test_stats.py, troi/musicbrainz/artist_credit_id_lookup.py, troi/musicbrainz/msb_mapping.py, troi/musicbrainz/recording_lookup.py, troi/musicbrainz/related_artist_credits.py, troi/musicbrainz/tests/test_ac_id_lookup.py, troi/musicbrainz/tests/test_msb_mapping.py, troi/musicbrainz/tests/test_recording_lookup.py, troi/musicbrainz/tests/test_related_artist_credits.py, troi/operations.py, troi/patch.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py, troi/playlist.py, troi/tests/test_entities.py, troi/tests/test_filters.py, troi/tests/test_operations.py, troi/tools/area_lookup.py, troi/tools/tests/test_area_lookup.py, troi/utils.py, troi/webserver/main.py
Some warnings and errors that my code checker was throwing up in the code
* A bunch of unused imports
* Some missing imports in code flows that we never hit
* Remove debug parameter from Element.read subclasses
* Clean up some arguments in subclasses, especially in @staticmethod-annotated methods
* Remove some unused code
* Should use `is` to check None, not equal
* Use `None` as a default empty argument, [instead of mutable `{}`](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)
=> Code cleanup / linting

troi/musicbrainz/genre_lookup.py, troi/musicbrainz/tests/test_genre_lookup.py
I used the `Recording.musicbrainz` dictionary to store this data, because that's where it comes from.
=> Add element to look up tags and genres on dataset hoster

troi/cli.py, troi/patches/ab_similar_recordings.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py
Instead of setting arguments for a patch by defining a dictionary, use a click command. This has a number of advantages:
* Use click's robust argument parsing, type checking, and standardised definition structure
* Automatically generate help, and use it in the `info` command
* explicitly name inputs in the `create` methods
=> LB-736: Use click to parse the arguments of patches

troi/acousticbrainz/annoy.py, troi/acousticbrainz/tests/test_annoy.py, troi/musicbrainz/tests/test_mbid_mapping.py
It appears that we have changed AB's similarity API endpoint when finalizing the annoy PR. Hence, the AnnoyElement in Troi needs to be fixed up as well. Notably, the recording_ids should now be passed as a query param and the JSON returned by the endpoint looks like the example in the updated test. This should hopefully resolve #38.
=> Update AnnoyElement to match the similarity api in AB prod

troi/__init__.py, troi/cli.py, troi/filters.py, troi/listenbrainz/dataset_fetcher.py, troi/listenbrainz/stats.py, troi/listenbrainz/user.py, troi/listenbrainz/yim_user.py, troi/loops.py, troi/patch.py, troi/patches/ab_similar_recordings.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py, troi/patches/patch_runner.py, troi/patches/playlist_from_mbids.py, troi/patches/top_discoveries_for_year.py, troi/patches/top_missed_recordings_for_year.py, troi/patches/top_new_recordings_you_listened_to_for_year.py, troi/patches/top_recordings_for_year.py, troi/patches/top_sitewide_recordings_for_year.py, troi/patches/weekly_flashback_jams.py, troi/patches/world_trip.py, troi/patches/yim_patch_runner.py, troi/playlist.py, troi/print_recording.py
This PR covers the work finishing YIM 2021 -- once again there are no tests, but a lot of code hammered out quickly to meet the deadline. The next PR will revisit tests for all the newly added features.
This PR implements the following:
- Add a user entity
- Add the concept of a script runner that can run scripts for a whole pile of users.
- Add the ability to query for active LB users.
- Some type checking debugging
- Improvements to what data elements an artist can have to make things more flexible.
- Cleanup of command line arguments to make submitting data for multiple users more clear
- Finish debugging the 4 patches used to create the YIM playlists.
The next PR will need to do some cleanup refactoring and add tests for all the new functions.
=> Teach troi for loops

requirements.txt, troi/acousticbrainz/tests/test_annoy.py, troi/playlist.py, troi/tests/test_filters.py, troi/tests/test_utils.py
we had 2 inconsistencies in the troi jspf output compared to the
documentation:
- track extension was https://musicbrainz.org/recording/ instead of
https://musicbrainz.org/doc/jspf#track
- key for the list of artist mbids was changed from artist_identifier
to artist_mbids, and we can't find a documentated motivation for
doing so. After discussion we decided to standardise on
artist_identifiers (plural, and keeps the 'identifier' terminology
already present in the jspf spec
=> LB-1058: Fix jspf playlist output 

troi/patches/area_random_recordings.py, troi/tools/area_lookup.py, troi/tools/tests/test_area_lookup.py
Quick fix to get the random area recordings working again. Still no tests. Changes include:
- Fetch artist mbids
- Fetch artist area mbid, not id
- Use dataset hoster to fetch the data, remove the old unneeded file
- Use improved PlaylistRedundancyReducerElement
=> Fix area random recordings

troi/patches/ab_similar_recordings.py
The arguments to the PlaylistMakerElement were in incorrect order.
=> Fix bug in ab-similar-recordings patch

troi/patches/daily_jams.py, troi/playlist.py
Before delving in and making daily-jams super fancy, I've made a simple stop-gap measure that zips together the top and similar recs, removes duplicate tracks and shuffles the result. This PR goes hand in hand with LB PR #2016. Once this is merged we should tag it and then reference that tag in the LB PR.
=> Improve daily jams

troi/patches/daily_jams.py
The patch to upload the generated playlist was failing because we are the function instead of its return value to the serialization function.
=> Fix serialization issue in daily jams

troi/core.py
To make it easier to use generate_playlist from a library, return the playlist element from it. Since we are now returning an element instead of boolean for success, it makes sense to return None instead of False for failure.
=> Return playlist element from generate_playlist

troi/listenbrainz/listens.py, troi/patches/daily_jams.py
We generate daily jams based on user's timezone in ListenBrainz. In many cases, these jams will get generated before yesterday's listens get imported in the Spark cluster. As a result the latest_listened_at timestamp, of the recommendations can be out of date. To fix this, retrieve all listens of the user from last 2 days and augument the latest_listened_at value of the recordings with those.
=> Add RecentListensTimestampLookup element

troi/__init__.py, troi/patches/playlist_from_listenbrainz.py, troi/playlist.py, troi/tests/test_playlist.py, troi/tests/test_utils.py
Add a method to de-serialize JSPF playlist to a `troi.Playlist` entity. Also, added a dummy patch for now but we may not want to put that in LB instead of troi or maybe go entirely some other way.
=> Add element to load a playlist from LB

troi/patches/daily_jams.py
It seems recommendations produced by spark have duplicates so pass those through a deduplicate filter first.
=> Deduplicate tracks in daily jams

troi/listenbrainz/listens.py, troi/musicbrainz/recording.py, troi/musicbrainz/recording_lookup.py, troi/patches/daily_jams.py
Users who regularly listen to daily jams start to see very less tracks in their playlists. Currently, we consider top 100 raw recs as the source of daily jams playlists and filter out any tracks listened in the past 14 days. Since recommendations don't change a lot on daily basis, most of the tracks get filtered.
To tackle this situation, we add the next 100 raw recommendations of the user to the source. Note that we do not fetch top 200 directly because that would mean an equal chance of recommending a track from 101-200 range as a track from 1-100. We don't want that, we want to prefer the top 100 over the next 100. Hence, only ask for more recordings if there is a shortfall.
=> Add more tracks to daily jams if needed

troi/internal/yim_patch_runner.py, troi/loops.py, troi/playlist.py
metabrainz/listenbrainz-server#2239 adds additional_metadata to replace alogrithm_metadata. algorithm_metadata is now a key inside the additional_metadata dict.
=> Use additional_metadata property instead of algorithm_metadata

troi/__init__.py, troi/core.py, troi/internal/yim_patch_runner.py, troi/loops.py, troi/playlist.py, troi/tests/test_playlist.py, troi/tools/spotify_lookup.py, troi/utils.py
1. Store external uris of the playlist in additional metadata.
2. Add methods to easily update additional metadata of the playlist. These are needed so that adding some metadata in a function does not override the existing data and so that we don't need to have such checks in multiple places.
3. Move DumpElement from utils to playlist to avoid circular import issues.
4. Export to spotify before uploading to LB so that the external url is uploaded to LB through additional_metadata.
5. Unrelated: fix a spotify playlist fixup when there are no alternative ids available to fix up tracks.
=> Improve support for additional playlist metadata

troi/playlist.py
Handle case if user has deleted spotify playlist
If the spotify url provided to update existing playlist returns an error, it means that the user may have unfollowed/deleted it from spotify. In that case, attempt to create a new playlist.
Do not attempt to update existing playlist if url is None
=> Improve spotify playlist handling

troi/patches/daily_jams.py
We may exhaust top 200 recordings for a user, in that case keep adding more recordings from ListenBrainz recommendations (we have 1000 available) till either the recordings from recommendations exhaust or we have a minimum recordings available for daily jams.
=> Use more recommendations if needed for daily jams

troi/listenbrainz/listens.py, troi/musicbrainz/recording_lookup.py, troi/musicbrainz/tests/test_recording_lookup.py
To reduce some of the "dupes", different recordings in MB but close enough for a listener consider canonical mbids of a recordings during filtering. As discussed in IRC, this is likely not going to be enough for weeding out all undesired recordings.
=> Consider canonical recordings in latest listen filter

troi/cli.py, troi/core.py, troi/internal/top_discoveries_for_year.py, troi/internal/top_missed_recordings_for_year.py, troi/internal/top_new_recordings_you_listened_to_for_year.py, troi/internal/top_recordings_for_year.py, troi/internal/top_sitewide_recordings_for_year.py, troi/patch.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py, troi/patches/playlist_from_listenbrainz.py, troi/patches/playlist_from_mbids.py, troi/patches/recs_to_playlist.py, troi/patches/weekly_flashback_jams.py, troi/patches/world_trip.py
To make it simpler to use troi as a library, we intend to remove click from the core lib. Click seemingly doesn't allow adding options/arguments to a command at runtime. So here's some cursed workaround it. I have only ported one patch for now so that we can discuss if the approach is fine.
=> Prototype click removal from core

troi/patches/daily_jams.py
Was using original recs not yet passed through recent listen filter in final playlist generation. Fix steps in pipeline to ensure filtered recs are used.
=> Fix daily jams filters

troi/patches/daily_jams.py
We no longer need to parse the jam date -- we're just naming the playlist with it, so just pass it through.
=> Make the date a pass-through value

requirements.txt, troi/playlist.py, troi/tests/test_playlist.py, troi/tools/spotify_lookup.py
We cannot add more than 100 tracks to a playlist, therefore break down submitting tracks into chunks. Earlier, we used to replace all tracks in one go. But replace endpoint doesn't take a position parameter to tell it which tracks should be removed. Therefore, we can't use it directly. The new workflow is to call replace items with an empty uris array to reset the playlist tracks. Then, call add items on each chunk of tracks to insert those.
=> LB-1216: Fix exporting large playlists to spotify

troi/core.py, troi/listenbrainz/feedback.py, troi/listenbrainz/listens.py, troi/listenbrainz/recs.py, troi/patches/daily_jams.py
Daily jams are failing for users in production due to ratelimit errors. The intent is to pass troi's auth token to the patch in prod so that the ratelimit can be bypassed.
=> Use an auth token for extended ratelimit

troi/patches/periodic_jams.py
In the previous PR the slug was set to period-jams, which doesn't allow us to distinguish between weekly-jams, daily-jams and weekly-new-jams. Setting the slug according to type fixes this.
=> Fix periodic patch slug

troi/print_recording.py
Print an extra column of ranking if the data is available. Useful for debugging perodic jams.
=> print ranking if available

troi/__init__.py, troi/patches/periodic_jams.py, troi/playlist.py
The bulk generation of playlists doesn't have good playlist descriptions, so this PR adds those to the troi patch, for easy reference from the listenbrainz codebase.
Also in this PR is support for expires_at in playlist's additional_metadata field, so that we know when a playlist is due to expire and can clearly show a timer icon to our users.
=> Add support for expires_at in additional_metadata and add descriptios for periodic playlists

troi/patches/periodic_jams.py, troi/playlist.py, troi/tools/spotify_lookup.py
So that we can submit bulk generated playlists from spark without creating unnecessary patch objects.
=> Separate spotify submission into a utility function

troi/patch.py, troi/patches/playlist_from_listenbrainz.py, troi/playlist.py
This PR opens the possibility for sending playlists that have not been saved to LB to be transferred to Spotify. This functionality will be used in LB radio.
=> Allow sending JSPF files to spotify

troi/musicbrainz/recording_lookup.py, troi/parse_prompt.py, troi/patches/lb_radio_classes/artist.py, troi/patches/lb_radio_classes/recs.py, troi/patches/lb_radio_classes/stats.py, troi/tests/test_parser.py
This PR improves a number of things:
- tags can now contain all latin characters if no parens are used. (e.g. tag:blümchen)
- tags can now contain unicode characters, if parens are used. (e.g. tag:(モーニング娘)
- use new popular recordings endpoint
- Use the metadata provided in the popular recordings endpoint
- Make recording lookup optional if no recordings need looking up.
- Implement common error detection and give better feedback.
=> Improve error handling for LB-radio

README.md, docs/lb_radio.rst, troi.py, troi/patches/lb_radio.py, troi/patches/lb_radio_classes/artist.py, troi/patches/lb_radio_classes/tag.py, troi/splitter.py, troi/utils.py
This PR improves the functionality of rag radio using similar tags for medium and hard mode. The addition of similar tags can be overridden with the nosim option. Other smaller tweaks to how the tag radio works were made (adjusting percent ranges, requiring minimum tag counts).
Finally add a troi.py file, which feels like it has been missing for a while.
The similar tags dataset is currently hosted on wolf, so that will need its own PR and release into labs API; once that is done,  I will open a new PR to start using the new production data.
=> Improve tag radio, add troi.py, use similar tags, other tag improvements

.github/workflows/ci.yml, docs/lb_radio.rst, tests/musicbrainz/test_recording_lookup.py, tests/test_parser.py, tests/test_playlist.py, troi/__init__.py, troi/cli.py, troi/core.py, troi/listenbrainz/recs.py, troi/musicbrainz/recording_lookup.py, troi/parse_prompt.py, troi/patch.py, troi/patches/area_random_recordings.py, troi/patches/lb_radio.py, troi/patches/lb_radio_classes/artist.py, troi/patches/lb_radio_classes/blend.py, troi/patches/lb_radio_classes/tag.py, troi/patches/periodic_jams.py, troi/patches/playlist_from_mbids.py, troi/patches/recs_to_playlist.py, troi/patches/top_discoveries_for_year.py, troi/patches/top_missed_recordings_for_year.py, troi/patches/weekly_flashback_jams.py, troi/playlist.py, troi/recording_search_service.py, troi/service.py, troi/utils.py
This PR extends troi in the following way:
- Create a registry for services that allow local resolution of content: artist_search and tag_search. By doing a local search against a local collection, we avoid the problems of having to resolve a playlist, which can often destroy that playlist. This required some refactoring of the artist and tag elements.
- Refactor how playlists are generated to be a little more streamlined.
- Add support for subsonic_ids in the musicbrainz metadata.
- Simplify the syntax of LB-Radio (disallow text not wrapped in () )
- Minor other bits of refactoring.
=> LB Radio Local

troi/patches/lb_radio_classes/playlist.py, troi/playlist.py
This PR fixes some problems with JSPF serialization:
The created_for element should be part of the extension.
track identifier should be a list not a string.
This PR must be released WITH the troi PR of the same branch name! That PR needs to be updated after this PR is merged and released.
=> Jspf cleanup

troi/patches/playlist_from_ms.py, troi/playlist.py, troi/tools/apple_lookup.py, troi/tools/common_lookup.py, troi/tools/spotify_lookup.py
- Added a new Patch ImportPlaylistPatch that creates a troi.playlist by importing Spotify Playlists
- Migrated some helper functions (get_tracks_from_spotify, mbid_mapping and etc.)
- Added a new Element to create a playlist based on track_names and artist_names (basically, works like playlist_from_mbid)
!!! It's not YET finished. I'm still testing the code with LB. I opened this pull request to track the changes and further commit them here.
=> A new Patch for importing playlists from Spotify

troi/tools/apple_lookup.py
In my recent commit, @/anshg1214 pointed out that Troi throws an error if a playlist lacks a description. I have resolved this issue by modifying the code to set the description to an empty string when none is provided
=> Fixed bug with description

pyproject.toml, troi/patches/playlist_from_ms.py, troi/tools/apple_lookup.py, troi/tools/common_lookup.py, troi/tools/soundcloud_lookup.py, troi/tools/spotify_lookup.py, troi/tools/utils.py
- Added SoundCloud playlist import support to `ImportPlaylistPatch`.
- Optimized code for Apple and Spotify playlist imports by removing unnecessary functions like `convert_track_to_json`.
NOTE: SoundCloud tracks store categories differently from Apple/Spotify as they do not store artist names separately. For starters, I implemented a small code snippet that splits the title into the artist name and track name. This code handles most SoundCloud tracks but does not cover all cases. We plan to implement a new function to identify SoundCloud title patterns and optimize the process for a broader set of tracks.
=> Import Playlists from SoundCloud

troi/content_resolver/artist_search.py, troi/content_resolver/subsonic.py, troi/patches/lb_radio_classes/artist.py
This change has a few fixes:
- For subsonic import, allow track and disc number to be None (and default to 1). Subsonic servers are **not** guaranteed to return values here. Tested on my Navidrome instance
- Multiple fixes for get_similar_artists: proper post parameter, parse response, query using list of ids (not dicts), and return an empty array for msgs
- For `artist.py`, in some cases the `artist_credit` is `None`, also allow for this (via `AttributeError`)
These changes were tested locally by importing via subsonic, importing metadata, and then doing `lbz-radio` with an artist, and then with a tag.
=> [bugfix]: Do not require Subsonic disc/track number, fix lb-radio artist locally

troi/patches/periodic_jams.py
LB-1599: Export to Spotify failed because the Weekly Mix playlist description was too long. Spotify only allows 300 characters max.
After discussing with aerozol and monkey, we decided to shorten the Weekly Mix description. I also shortened the Weekly Exploration description to prevent future export failures.
=> LB-1599: Weekly Mix export to Spotify fails (description too long)

troi/__init__.py, troi/cli.py, troi/patch.py, troi/patches/playlist_from_ms.py, troi/playlist.py, troi/tools/soundcloud_lookup.py, troi/tools/spotify_lookup.py, troi/tools/utils.py
PR Status: In Progress
- Developed a SoundCloud API class to manage SoundCloud interactions.
- Implemented SoundCloud lookup features, including:
- Fixes for unplayable tracks.
- SoundCloud Labs API ID lookup.
- Submission functionality to SoundCloud.
=> SoundCloud Export & Lookup

troi/patches/playlist_from_ms.py, troi/tools/common_lookup.py, troi/tools/soundcloud_lookup.py, troi/tools/utils.py
Thanks to @anshg1214 for highlighting this in the [PR](https://github.com/metabrainz/listenbrainz-server/pull/2965#pullrequestreview-2271886561). We noticed that importing playlists from SoundCloud wasn't functioning correctly
The issue stemmed from the endpoint output. After updating the API callback to support pagination, it returned tracks but omitted playlist details.
I discovered that the playlist endpoint doesn’t support pagination, so I implemented a separate endpoint specifically for fetching the playlist name and description.
This approach seems effective, and I’m considering applying a similar solution for other services
=> SoundCloud import tracks fix

troi/content_resolver/artist_search.py, troi/content_resolver/unresolved_recording.py, troi/musicbrainz/mbid_mapping.py, troi/musicbrainz/recording_lookup.py, troi/musicbrainz/related_artist_credits.py, troi/patches/lb_radio.py, troi/patches/lb_radio_classes/artist.py, troi/patches/lb_radio_classes/collection.py, troi/patches/lb_radio_classes/country.py, troi/patches/lb_radio_classes/playlist.py, troi/playlist.py, troi/recording_search_service.py, troi/tools/area_lookup.py
LB-1628 points out that LB Radio is crap at dealing with rate limiting, so this PR ensures that request calls handle 439/503 correctly. 
Also, for some queries more than 1,000 items were generated, which caused problems. Truncating to first 1,000 tracks is a sufficient fix for this.
=> LB-1628: LB radio 429 fix

troi/tools/spotify_lookup.py
As reported in https://tickets.metabrainz.org/browse/LB-1514, the ImportPlaylistPatch is limited to 100 tracks per playlist, even if there are more in that playlist.
This is because the spotipy playlist_items method (and the underlying spotify api endpoint) only allows fetching 100 tracks at a time.
To get all the tracks in a playlist, we need to call this endpoint repeatedly with an offset updated each loop.
=> Get all tracks from spotify playlist

docs/user-guide.rst
`resolve subsonic` or `troi resolve subsonic` did not work for me, but looks like this is now `troi db subsonic`.
This still times out against my funkwhale server
=> Update user-guide.rst: resolve subsonic -> troi db subsonic

troi/playlist.py, troi/tools/apple_lookup.py, troi/tools/utils.py
Following #153, fixing the same issue for Apple Music.
The current implementation using the Apple Music API "?include=tracks" only returns the first 100 tracks with no pagination option.
To get the rest of the tracks if there are more, we need to fetch them separately using another endpoint ("/tracks"). Thankfully we can reuse the included tracks from the first call and start at offset 100.
=> LB-1700: Get all tracks for apple music playlist
