README.md
Fixed Incorrect spelling in readme.md of accomplish (accomlish)
=> Fixed spelling error #3

troi.py
Some things that I ran into while trying to run patches
=> Some cleanups to troi.py entrypoint

.gitignore, docs/Makefile, docs/conf.py, docs/index.rst, docs/make.bat
LB-737
This is just a stub docs directory so that we can build it and publish on readthedocs. We need to continue by adding an intro and linking into the existing files.
=> Initial version of docs

troi.py, troi/__init__.py, troi/acousticbrainz/annoy.py, troi/listenbrainz/area_random_recordings.py, troi/listenbrainz/recs.py, troi/musicbrainz/artist_credit_id_lookup.py, troi/musicbrainz/msb_mapping.py, troi/musicbrainz/recording_lookup.py, troi/musicbrainz/related_artist_credits.py, troi/playlist.py, troi/tools/area_lookup.py, troi/webserver/main.py
=> Exception cleanup (fixing LB-743)

.gitignore, setup.py, troi/cli.py, troi/utils.py
=> Add support for loading patches from the patches directory in the current directory.

setup.py, troi/__init__.py, troi/listenbrainz/area_random_recordings.py, troi/listenbrainz/recs.py, troi/listenbrainz/tests/test_area_random_recordings.py, troi/musicbrainz/tests/test_recording_lookup.py, troi/musicbrainz/tests/test_related_artist_credits.py, troi/patches/area_random_recordings.py, troi/tests/test_entities.py, troi/tests/test_utils.py, troi/tools/area_lookup.py, troi/tools/tests/test_area_lookup.py
This adds tests for core functionality. At this point the most important modules/features seem covered -- we should discuss what other modules/functions need more tests.
=> Adding more tests

troi/__init__.py, troi/acousticbrainz/annoy.py, troi/cli.py, troi/filters.py, troi/listenbrainz/area_random_recordings.py, troi/listenbrainz/recs.py, troi/listenbrainz/stats.py, troi/listenbrainz/tests/test_stats.py, troi/musicbrainz/artist_credit_id_lookup.py, troi/musicbrainz/msb_mapping.py, troi/musicbrainz/recording_lookup.py, troi/musicbrainz/related_artist_credits.py, troi/operations.py, troi/patch.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py, troi/playlist.py, troi/utils.py, troi/webserver/main.py
WIP -- logging statements added as an example. Current output:
INFO:DailyJamsPatch:this is a log message
INFO:DailyJamsElement:element log message
. .
=> LB-740: Implement logging functions

troi/musicbrainz/tests/test_ac_id_lookup.py, troi/musicbrainz/tests/test_msb_mapping.py, troi/musicbrainz/tests/test_related_artist_credits.py
Fixes tests that were broken in #23, and configures jenkins for tests
=> Fix requests tests

.travis.yml
=> Stop using travis in favor of brainzbot.

troi/acousticbrainz/annoy.py, troi/acousticbrainz/tests/test_annoy.py, troi/filters.py, troi/patches/ab_similar_recordings.py, troi/tests/test_filters.py, troi/tests/test_utils.py
Initial version that just hits AB, we had some more ideas to add to it:
* filter by similar artists to the input recording
* filter recordings from a given year/range
Should be merged after #10
=> Annoy similarity

troi/__init__.py, troi/acousticbrainz/tests/test_annoy.py, troi/filters.py, troi/patches/ab_similar_recordings.py, troi/patches/area_random_recordings.py, troi/patches/daily_jams.py, troi/playlist.py, troi/tools/area_lookup.py, troi/webserver/main.py
Remove RuntimeError exception in favour of our troi-specific subclass, PipelineError
Small fix for a failing annoy test that I merged in #11
=> Remove runtimeerror

troi/filters.py, troi/musicbrainz/tests/test_year_lookup.py, troi/musicbrainz/year_lookup.py, troi/tests/test_filters.py
Not much to say, there should be no real surprises here.
=> Add a year lookup element

troi/sorts.py, troi/tests/test_sorts.py
=> Add YearSortElement

.github/workflows/python-app.yml
Migrate running tests to Github Actions.
=> Add action for running tests

troi/patches/ab_similar_recordings.py
=> Fix AB patch argument parsing

troi/internal/top_sitewide_recordings_for_year.py, troi/patches/weekly_flashback_jams.py, troi/playlist.py
LB-1087
Need to fix invalid method argument name and replace obsolete year lookup element with mbid mapping element.
=> LB-1087: Get weekly flashback jams working again

requirements.txt, setup.py, troi/cli.py, troi/core.py, troi/musicbrainz/mbid_mapping.py, troi/patches/recs_to_playlist.py, troi/playlist.py
Just trying to have few places where it crashes, so adding more checks for when data is missing and doing the right thing instead.
=> Making sure that print recording and mbid_mapping are more robust

troi/patches/recs_to_playlist.py
recs-to-playlist patch supports top and artist already, also add support for raw recommendations.
=> Add raw recommendations to recs_to_playlist patch

troi/patches/daily_jams.py
We want to create daily jams playlists in LB based on user timezones so that those are ready by the time they wake up. This means that the patch needs to take into account timezones when calculating the jam date to display to users. One way to do that would be to accept a timezone parameter and let the patch calculate the current day based on that. But the other way to accept a jam date directly seems more flexible and easier so doing that.
=> Accept jam_date as optional argument in daily-jams patch

troi/musicbrainz/genre_lookup.py, troi/musicbrainz/tests/test_genre_lookup.py, troi/print_recording.py
This PR is mostly to not waste the genre improvements I did trying to implement some "energy" classification using genres. That approach seems far fetched, but having a better genre lookup is a worthwhile result, so creating a PR to note waste this code.
=> Use metadata lookup to lookup genres now.

troi/__init__.py, troi/listenbrainz/stats.py, troi/listenbrainz/tests/test_stats.py, troi/operations.py, troi/tests/test_entities.py, troi/tests/test_playlist.py
Both of these fields have been removed from LB, so remove from troi as well. recording_msid still exists in LB so keeping in troi as well.
=> Remove artist_msid and release_msid

troi/patches/daily_jams.py
Daily jams is still getting a lot of repeats and I have interest in my jams because I've listened them all to death! :)
=> Increase DAYS_OF_RECENT_LISTENS_TO_EXCLUDE to 60 days

troi/filters.py, troi/listenbrainz/feedback.py, troi/patches/daily_jams.py, troi/tests/test_filters.py
Remove user's hated recordings from daily jams playlist.
=> Add filter for hated recordings

troi/patches/top_missed_recordings_for_year.py
We have two db connections. One to primary LB db which stores "user" table and similar users data. The other connection is to TS db which store tracks_of_the_year data. Update the connection usage in the patch accordingly. And some minor refactorings.
=> Misc fixes for TopMissedTracksPatch

troi/patches/daily_jams.py, troi/playlist.py
I hereby open this PR in from the deep sense of internet duties that must be carried out.
( I hope the cryptic PR desc will be forgiven for this occasion of upmost importance )
=> Carrying out my civic internet duties

troi/musicbrainz/recording_lookup.py, troi/patches/lb_radio_classes/recs.py
Was checking for "", should be None.
Also, remove debug prints
=> Fix the stats that are not fetching metadata

README.md, pyproject.toml
Improve the readme to be more current so that the PyPi page looks nicer.
=> Improve project verbiage

troi/playlist.py
Parsing the values already written to JSPF was forgotten in previous PR, so adding now.
=> Read subsonic ids and locations from jspf

troi/core.py
Fixed the list_patches function, removed the object of a static method.
=> LB-1502 Fix troi cli list command

troi/print_recording.py
Work in progress, to be tested later
if recordings.musicbrainz had a 'popularity' key, then the commits will print the rows corresponding to popularity
=> LB-1503: popularity key in recordings.musicbrainz

troi/external/gpt.py, troi/patches/ai_jams.py
Use OpenAI API to retrieve recordings for a given prompt in json, lookup mbids for the same using labs api and generate a playlist.
=> AI Jams: a simple demo for creating new patches and elements

troi/__init__.py, troi/cli.py, troi/patch.py, troi/playlist.py, troi/tools/apple_lookup.py, troi/tools/spotify_lookup.py, troi/tools/utils.py
I added the necessary functions for exporting to Apple Music. To keep the code organized, I created a class for Apple API calls in the utils folder.
=> Exporting playlist to Apple Music

troi/patches/lb_radio.py, troi/patches/lb_radio_classes/artist.py
The nosim option for artists was not respected, this, combined with the already merged PR in LB fixes that issue.
=> Artist nosim fix

troi/tools/utils.py
While creating a playlist in Apple Music, the response is not being returned throwing an error.
=> Fix playlist export to Apple Music

tests/musicbrainz/test_recording_lookup.py, troi/listenbrainz/recs.py, troi/musicbrainz/recording_lookup.py, troi/patches/periodic_jams.py
Hopefully this will finally unblock daily jams!
=> Yet more rate limiting improvements by passing the troi auth token

tests/test_filters.py, troi/filters.py, troi/patches/periodic_jams.py, troi/playlist.py
=> LB-1731: Create daily jams for users who don't have enough listens

troi/cli.py, troi/patch.py, troi/playlist.py, troi/tools/soundcloud_lookup.py
Fix adding soundcloud url, remove unused soundcloud user id option.
=> Cleanup soundcloud export
